// Auto-generated by LibreLane
module system_top_pad_wrapper(
`ifdef USE_POWER_PINS
  inout VSS,
  inout VDD,
`endif
  input clk,
  output clk_PU,
  output clk_PD,
  input rst_n,
  output rst_n_PU,
  output rst_n_PD,
  input sck,
  output sck_PU,
  output sck_PD,
  input cs_n,
  output cs_n_PU,
  output cs_n_PD,
  input mosi,
  output mosi_PU,
  output mosi_PD,
  output miso_CS,
  output miso_SL,
  output miso_IE,
  output miso_oe,
  output miso_PU,
  output miso_PD,
  output miso_OUT,
  input miso_IN,
  input uart_rx,
  output uart_rx_PU,
  output uart_rx_PD
);
endmodule
