SIM ?= icarus
TOPLEVEL_LANG ?= verilog

VERILOG_SOURCES += ../delay_line.sv

TOPLEVEL = delay_line

COCOTB_TEST_MODULES = tb_delay_line

WAVES=1

include $(shell cocotb-config --makefiles)/Makefile.sim