// Auto-generated by LibreLane
module system_top(
`ifdef USE_POWER_PINS
  inout VDD,
  inout VSS,
`endif
  input clk,
  input rst_n,
  input sck,
  input cs_n,
  input mosi,
  output miso,
  output miso_oe,
  input uart_rx
);
endmodule
