# GF180MCU LibreLane config -- FIR filter macro
meta:
  version: 3
  flow: Classic

DESIGN_NAME: system_top
VERILOG_FILES:
  - dir::../src/generic/regfile.sv
  - dir::../src/generic/fwft_fifo.sv
  - dir::../src/uart_programming/programmer.sv
  - dir::../src/uart_programming/uart_rx.sv
  - dir::../src/system_top.sv
  - dir::../src/spi-axi/spi_slave.sv
  - dir::../src/spi-axi/spi_axis_top.sv
  - dir::../src/fir/fir_control.sv
  - dir::../src/fir/fir_top.sv
  - dir::../src/fir/delay_line/delay_line.sv
  - dir::../src/fir/mac/mac.sv

# SystemVerilog Plugin 
USE_SLANG: True
SLANG_ARGUMENTS: ['--keep-hierarchy']

CLOCK_PORT: clk
CLOCK_PERIOD: 40

# Die area: 1100x550 um absolute
FP_SIZING: absolute
DIE_AREA: [0.0, 0.0, 800.0, 600.0]

# Power / ground nets.
VDD_NETS:
  - VDD
GND_NETS:
  - VSS

# Signoff / streamout.
PRIMARY_GDSII_STREAMOUT_TOOL: klayout

# Routing / ESD.
DIODE_ON_PORTS: in
RT_MAX_LAYER: Metal4
PDN_MULTILAYER: false

# Power distribution network (straps + pitch).
PDN_VWIDTH: 3
PDN_HWIDTH: 3
PDN_VSPACING: 1
PDN_HSPACING: 1
PDN_VPITCH: 70
PDN_HPITCH: 70
PDN_EXTEND_TO: boundary

# Placement.
PL_TARGET_DENSITY_PCT: 65
MAX_FANOUT_CONSTRAINT: 10
GPL_CELL_PADDING: 2
DPL_CELL_PADDING: 2

# Multiplier optimization
SYNTH_MUL_BOOTH: true

# Margins.
TOP_MARGIN_MULT: 1
BOTTOM_MARGIN_MULT: 1
LEFT_MARGIN_MULT: 6
RIGHT_MARGIN_MULT: 6