# GF180MCU LibreLane config -- FIR filter macro
meta:
  version: 3
  flow: Classic
  substituting_steps:
    OpenROAD.IRDropReport: null
DESIGN_NAME: system_top_pad_wrapper
VERILOG_FILES:
  - dir::../src/generic/regfile.sv
  - dir::../src/generic/fwft_fifo.sv
  - dir::../src/uart_programming/programmer.sv
  - dir::../src/uart_programming/uart_rx.sv
  - dir::../src/system_top.sv
  - dir::../src/system_top_pad_wrapper.sv
  - dir::../src/spi-axi/spi_slave.sv
  - dir::../src/spi-axi/spi_axis_top.sv
  - dir::../src/fir/fir_control.sv
  - dir::../src/fir/fir_top.sv
  - dir::../src/fir/delay_line/delay_line.sv
  - dir::../src/fir/mac/mac.sv
# SystemVerilog Plugin 
USE_SLANG: True
SLANG_ARGUMENTS: ['--keep-hierarchy']
# Clock
CLOCK_PORT: clk
CLOCK_NET: clk
CLOCK_PERIOD: 62.5
# Die area: 1100x550 um absolute
FP_DEF_TEMPLATE: dir::padring/BH/A20_BH.def
FP_TEMPLATE_MATCH_MODE: permissive
FP_TEMPLATE_COPY_POWER_PINS: true
PDN_ENABLE_PINS: false
FP_SIZING: absolute
DIE_AREA: [0, 0, 1110, 550]
CORE_AREA: [10, 10, 1100, 540]
ERROR_ON_PDN_VIOLATIONS: false
# Power / ground nets.
VDD_NETS:
  - VDD
GND_NETS:
  - VSS
# Signoff / streamout.
PRIMARY_GDSII_STREAMOUT_TOOL: klayout
# Routing / ESD.
DIODE_ON_PORTS: in
# IO_PIN_ORDER_CFG: dir::pin_order.cfg
RT_MAX_LAYER: Metal3
PDN_MULTILAYER: true
# Power distribution network (straps + pitch).
PDN_VWIDTH: 1.6
PDN_HWIDTH: 1.6
PDN_VSPACING: 1
PDN_HSPACING: 1
PDN_VPITCH: 75
PDN_HPITCH: 75
PDN_CORE_RING: True
PDN_CORE_RING_VOFFSET: 2
PDN_CORE_RING_HOFFSET: 2
PDN_CORE_VERTICAL_LAYER: Metal2
PDN_CORE_HORIZONTAL_LAYER: Metal3
PDN_CORE_RING_ALLOW_OUT_OF_DIE: False
PDN_CORE_RING_CONNECT_TO_PADS: True
PDN_CFG: dir::pdn_cfg.tcl
# Placement.
PL_TARGET_DENSITY_PCT: 75
MAX_FANOUT_CONSTRAINT: 10
MAX_CAPACITANCE_CONSTRAINT: 0.4
GRT_ALLOW_CONGESTION: true
GPL_CELL_PADDING: 1
DPL_CELL_PADDING: 1
# Timing and DRV Optimization
SYNTH_STRATEGY: "DELAY 4"
SYNTH_SIZING: true
SYNTH_ABC_BUFFERING: true
PL_RESIZER_DESIGN_OPTIMIZATIONS: true
PL_RESIZER_MAX_WIRE_LENGTH: 300
RUN_POST_CTS_RESIZER_TIMING: true
RUN_POST_GRT_RESIZER_TIMING: true
PL_RESIZER_SETUP_MAX_BUFFER_PCT: 50
GRT_RESIZER_SETUP_MAX_BUFFER_PCT: 50
PL_RESIZER_SETUP_SLACK_MARGIN: 1.5
GRT_RESIZER_SETUP_SLACK_MARGIN: 1.5
RUN_POST_GRT_DESIGN_REPAIR: true
DESIGN_REPAIR_MAX_WIRE_LENGTH: 200
DESIGN_REPAIR_MAX_SLEW_PCT: 10
GRT_DESIGN_REPAIR_MAX_WIRE_LENGTH: 200
GRT_DESIGN_REPAIR_MAX_SLEW_PCT: 5
MAX_TRANSITION_CONSTRAINT: 2.5
PNR_SDC_FILE: dir::custom.sdc
SIGNOFF_SDC_FILE: dir::custom.sdc
FALLBACK_SDC: dir::custom.sdc

# Multiplier optimization
SYNTH_MUL_BOOTH: true
# Margins.
TOP_MARGIN_MULT: 1
BOTTOM_MARGIN_MULT: 1
LEFT_MARGIN_MULT: 6
RIGHT_MARGIN_MULT: 6
